### ISSUE TITLE
error : fork/exec ... no such file or directory

### ISSUE THREAD

**Issue by ParaSpl01t** [zyrouge/pho#1]
Congrats on your first issue for this project. And sorry for being the first one to bother you.
OS: Arch Linux x86_64
libappimage version : 1.0.4.5-5
```
[~] ➤ pho install github ONLYOFFICE/appimage-desktopeditors

>   Name            Appimage-Desktopeditors
>   Identifier      onlyoffice-appimage-desktopeditors
>   Version         v7.4.1
>   Filename        DesktopEditors-x86_64.AppImage
>   AppImage        /home/para/.local/share/pho/applications/onlyoffice-appimage-desktopeditors/Appimage-Desktopeditors.AppImage
>   .desktop file   /home/para/.local/share/applications/onlyoffice-appimage-desktopeditors.desktop
>   Download Size   341.87 MB

? Do you want to proceed? yes

[1/1] ! Appimage-Desktopeditors v7.4.1 (3m:9s)
error: fork/exec /home/para/.local/share/pho/applications/onlyoffice-appimage-desktopeditors/Appimage-Desktopeditors.AppImage: no such file or directory

[~] ➤ ls /home/para/.local/share/pho/applications/onlyoffice-appimage-desktopeditors/Appimage-Desktopeditors.AppImage
Permissions Size User Date Modified    Name
.rwxr-xr-x  342M para 2023-10-09 14:58 /home/para/.local/share/pho/applications/onlyoffice-appimage-desktopeditors/Appimage-Desktopeditors.AppImage
```
Just downloaded the pho binary, pasted the binary into `./.local/bin` and ran `pho init`.  The rest is in the output above. The file is downloaded successfully.

Installing the downloaded file gives this error :
```
[~] ➤ pho install local /home/para/.local/share/pho/applications/onlyoffice-appimage-desktopeditors/Appimage-Desktopeditors.AppImage
? What should be the Application ID? appimage-desktopeditorsappimage
? What is name of the Application? Appimage-Desktopeditorsappimage

>   Name            Appimage-Desktopeditorsappimage
>   Identifier      appimage-desktopeditorsappimage
>   Version         0.0.0
>   AppImage        /home/para/.local/share/pho/applications/appimage-desktopeditorsappimage/Appimage-Desktopeditorsappimage.AppImage
>   .desktop file   /home/para/.local/share/applications/appimage-desktopeditorsappimage.desktop

? Do you want to proceed? yes

[1/1] ! Appimage-Desktopeditorsappimage 0.0.0 (1s)
error: mkdir /home/para/.local/share/pho/applications/appimage-desktopeditorsappimage/temp: file exists
```

**Comment by ParaSpl01t** [comment]
Additional info

**Comment by zyrouge** [comment]
> Congrats on your first issue for this project. And sorry for being the first one to bother you. OS: Arch Linux x86_64 libappimage version : 1.0.4.5-5
> 
> ```
> [~] ➤ pho install github ONLYOFFICE/appimage-desktopeditors
> 
> >   Name            Appimage-Desktopeditors
> >   Identifier      onlyoffice-appimage-desktopeditors
> >   Version         v7.4.1
> >   Filename        DesktopEditors-x86_64.AppImage
> >   AppImage        /home/para/.local/share/pho/applications/onlyoffice-appimage-desktopeditors/Appimage-Desktopeditors.AppImage
> >   .desktop file   /home/para/.local/share/applications/onlyoffice-appimage-desktopeditors.desktop
> >   Download Size   341.87 MB
> 
> ? Do you want to proceed? yes
> 
> [1/1] ! Appimage-Desktopeditors v7.4.1 (3m:9s)
> error: fork/exec /home/para/.local/share/pho/applications/onlyoffice-appimage-desktopeditors/Appimage-Desktopeditors.AppImage: no such file or directory
> 
> [~] ➤ ls /home/para/.local/share/pho/applications/onlyoffice-appimage-desktopeditors/Appimage-Desktopeditors.AppImage
> Permissions Size User Date Modified    Name
> .rwxr-xr-x  342M para 2023-10-09 14:58 /home/para/.local/share/pho/applications/onlyoffice-appimage-desktopeditors/Appimage-Desktopeditors.AppImage
> ```
> 
> Just downloaded the pho binary, pasted the binary into `./.local/bin` and ran `pho init`. The rest is in the output above. The file is downloaded successfully.
> 
> Installing the downloaded file gives this error :
> 
> ```
> [~] ➤ pho install local /home/para/.local/share/pho/applications/onlyoffice-appimage-desktopeditors/Appimage-Desktopeditors.AppImage
> ? What should be the Application ID? appimage-desktopeditorsappimage
> ? What is name of the Application? Appimage-Desktopeditorsappimage
> 
> >   Name            Appimage-Desktopeditorsappimage
> >   Identifier      appimage-desktopeditorsappimage
> >   Version         0.0.0
> >   AppImage        /home/para/.local/share/pho/applications/appimage-desktopeditorsappimage/Appimage-Desktopeditorsappimage.AppImage
> >   .desktop file   /home/para/.local/share/applications/appimage-desktopeditorsappimage.desktop
> 
> ? Do you want to proceed? yes
> 
> [1/1] ! Appimage-Desktopeditorsappimage 0.0.0 (1s)
> error: mkdir /home/para/.local/share/pho/applications/appimage-desktopeditorsappimage/temp: file exists
> ```

Seems like installation failed for some reason. You don't need to manually use the `install local` command after `install github`.

**Comment by ParaSpl01t** [comment]
I'm aware. I was just testing to see if local install will work

**Comment by zyrouge** [comment]
I probably guess it failed to extract the AppImage before it is being integrated. Can you try using `tidy-broken` command (deletes failed installation files) and running the install command again?

**Comment by ParaSpl01t** [comment]
Worked! thanks.

**Comment by zyrouge** [comment]
I guess the issue has been resolved. Closing this.
