### ISSUE TITLE
[Feature] pho add --link [name]

### ISSUE THREAD

**Issue by alyssadev** [zyrouge/pho#13]
Use case: On installing streamlink/streamlink-twitch-gui and streamlink/streamlink-appimage with pho, streamlink-twitch-gui wasn't able to easily find the streamlink binary, as it hadn't been added to the path. This feature would add an optional `--link -l` parameter to let the user set a symlink name that would be added to `.local/bin` or another configurable personal binary storage directory so the given AppImage is present in the path.

Current:

    $ pho add github streamlink/streamlink-appimage
    $ streamlink # not found

Expected:

    $ pho add github -l streamlink streamlink/streamlink-appimage
    $ streamlink # works

**Comment by zyrouge** [comment]
This seems like a good solution. But you can use `alias=pho run ...` for now.

**Comment by alyssadev** [comment]
That's very simple, I agree. shell completion on `pho run` would help with that flow as well, aliases and symlinks might not be necessary in that case

**Comment by zyrouge** [comment]
It's still experimental, kindly test it out.
