### ISSUE TITLE
cannot execute binary file: Exec format error

### ISSUE THREAD

**Issue by Pescu123** [zyrouge/pho#2]
OS: Gentoo Linux x86_64
Every time I tried to use the pho self-update command I had to reinstall the app manually for it to work. When I try to use it after the self-update command it always returns `exec format error: pho`
![image](https://github.com/zyrouge/pho/assets/42257807/8bdf2c0b-1d05-421a-bb96-acb84113b19a)
I installed pho in _/usr/local/bin/_

**Comment by Pescu123** [comment]
![image](https://github.com/zyrouge/pho/assets/42257807/5777c75c-7be5-440f-a2cb-25a581e89fde)
`/usr/local/bin/pho: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, Go BuildID=26NlcqdFZ9mApeKpmB-f/d-l02CSX6rLjYsxdAoWB/7_rg8S42IpWCT9pRcU8k/b1jqWN2VIeqdEUDWyRZi, stripped
`

**Comment by Pescu123** [comment]
Also this is an unrelated issue, but when I try to install a new appimage the command in the .desktop file is only the name of the executable file without the location. Because of that the desktop shortcuts no longer work and I need to update each one individually.

![image](https://github.com/zyrouge/pho/assets/42257807/4256c5d9-0156-46f4-b032-6b1d0e98ddc7)

 ```             
[Desktop Entry]
Type=Application
Encoding=UTF-8
Name=OpenRGB
Comment=Control RGB lighting
Exec=OpenRGB
Terminal=false
Categories=Utility;
Icon=/home/pescu/Applications/openrgb/Openrgb.png
```

**Comment by zyrouge** [comment]
> ![image](https://user-images.githubusercontent.com/42257807/274591667-3cd5a215-ea40-47b6-a0db-c498027dbc9e.png) `/usr/local/bin/pho: ELF 64-bit LSB executable, ARM aarch64, version 1 (SYSV), statically linked, Go BuildID=a015ChDlJzjX4SgXymta/9mIIXSCMosz3GxC_U_U4/QZeKR2qXouxgMNQPxZU7/bOoKXpYn9A4k9UtSH95k, stripped `
> 
> It looks like the self updater is downloading the arm version of the app

That's a weird issue, the update was bugged in old versions. Let me know if that happens with next update.

**Comment by Pescu123** [comment]
> Seems like that `.desktop` file embedded within the AppImage did not use `AppRun`. Should have replaced if it was using that. I'll have to fix this.

The same apps worked before updating from version 0.4 directly to 0.9.

**Comment by zyrouge** [comment]
> > Seems like that `.desktop` file embedded within the AppImage did not use `AppRun`. Should have replaced if it was using that. I'll have to fix this.
> 
> The same apps worked before updating from version 0.4 directly to 0.9.

Has been fixed in https://github.com/zyrouge/pho/commit/f389502c9f613d9a5178c9f1d5c01dfd844419cb.

**Comment by zyrouge** [comment]
Feel free to create a new issue if you find any bugs.
