### ISSUE TITLE
pho desktop files not showing up

### ISSUE THREAD

**Issue by Sush-ruta** [zyrouge/pho#24]
Hi,
Recently, *new* apps installed using `pho` are not showing up in the applications menu. I checked the cause. New apps are creating a desktop file with the `exec` field inside quotes, which is why it is not being recognised. For example, this was a .desktop file created by `pho`:
`"env APPIMAGELAUNCHER_DISABLE=1 /home/x/.local/share/pho/applications/unyo/unyo.AppImage"`
Removing the "" made the desktop file appear. I tried this with 2-3 apps with the same result.

**Comment by zyrouge** [comment]
Fixed in 6cf2af3bdf19c826db8a81cf3c3d3dc0309f793b.
