### ISSUE TITLE
Android Studio desktop file malformed after update

### ISSUE THREAD

**Issue by parkerlreed** [zyrouge/pho#25]
env and the appimage aren't quoted causing it to fail to launch

![image](https://github.com/user-attachments/assets/256de611-056e-4941-afaf-7b3118975f91)

```
[parker@parker-framework ~]$ pho update

Index   Application ID   Old Version    New Version 
1.      android-studio   v2024.1.1.12   v2024.1.1.13

? Do you want to proceed? yes

[1/1] √ android-studio v2024.1.1.13 (1m:15s)

√ Updated 1 applications successfully!
```

```
[Desktop Entry]
Version=1.1
Type=Application
Name=Android Studio (Beta)
Icon=/home/parker/.local/share/pho/applications/android-studio-beta/android-studio-beta.png
Exec=env APPIMAGELAUNCHER_DISABLE=1 /home/parker/.local/share/pho/applications/android-studio-beta/android-studio-beta.AppImage %f
Comment=The Drive to Develop
Categories=Development;IDE;
Terminal=false
StartupWMClass=jetbrains-studio
StartupNotify=true[Desktop Entry]

```

**Comment by zyrouge** [comment]
I don't think quotes cause this issue. They are necessary only if the path contains spaces. Try running `env APPIMAGELAUNCHER_DISABLE=1 /home/parker/.local/share/pho/applications/android-studio-beta/android-studio-beta.AppImage %f` and see if it works.

**Comment by parkerlreed** [comment]
This appears to be working again after reinstalling Android Studio on the latest pho version.
