### ISSUE TITLE
Add an option to install "Pre-release" versions

### ISSUE THREAD

**Issue by cinnamonmatexfce** [zyrouge/pho#3]
What I nice tool I just discovered! Well done! 😎

I'm asking here if you mind adding the feature to also grab `Pre-release` versions when installing via `pho install github owner/repo`.

Thanks again, for this nice AppImage manager!! 

________________________________________________________________________

Sorry, I forgot to add a pratical example specific to my personale use-case (I suppose this could be a "tricky" one):

 - [https://github.com/flyinghead/flycast](Flycast) has also a separate page for *fresh* builds, please have a look at here > https://flyinghead.github.io/flycast-builds/

**Comment by zyrouge** [comment]
Unfortunately, I cannot help you with supporting https://flyinghead.github.io/flycast-builds/ since it is very specific to their service.

**Comment by cinnamonmatexfce** [comment]
> Unfortunately, I cannot help you with supporting https://flyinghead.github.io/flycast-builds/ since it is very specific to their service.

NP. And thanks for the added feature, btw. 💫
